# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        exclude: (backend/static/img|frontend/assets)
    -   id: check-case-conflict
# pyright pre-commit hook
-   repo: local
    hooks:
    -   id: pyright
        name: Running PyRight Type Check
        entry: pyright
        language: system
        types: [python]
# Ruff pre-commit hook
-   repo: local
    hooks:
    -   id: ruff
        name: Running Ruff Linter
        entry: ruff
        language: system
        types: [python]
        args: [
            "check",
            "-q",
            "--fix",
            "--config",
            "./pyproject.toml"
        ]
